services:
  postgres:
    image: postgres:15
    container_name: postgres_prisma
    restart: unless-stopped
    environment:
      POSTGRES_USER: indra
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: prisma_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
